// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: oberon.flex

package scanner;

import exceptions.*;
import java.lang.Integer;


@SuppressWarnings("fallthrough")
public class OberonScanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\u10fe\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\0\1\3\22\0\1\1\2\0"+
    "\1\4\2\0\1\5\1\0\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\0\1\15\7\16\2\17\1\20"+
    "\1\21\1\22\1\23\1\24\2\0\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\2\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\36\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\36\1\52\1\36\1\53\1\0"+
    "\1\54\3\0\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\2\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\36\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\36\1\52\1\36\1\0\1\55\1\0\1\56\261\0"+
    "\2\57\115\0\1\60\u0180\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[768];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\2\14\1\15\1\16\1\17"+
    "\1\20\1\21\16\22\1\23\1\24\1\25\1\1\5\0"+
    "\2\26\1\27\1\30\1\31\1\32\5\22\1\33\1\0"+
    "\2\22\1\34\2\22\1\35\1\36\7\22\1\34\1\0"+
    "\2\37\1\0\2\26\4\22\2\40\1\22\1\0\1\41"+
    "\1\22\1\42\5\22\1\43\1\22\1\0\1\22\2\0"+
    "\1\44\1\37\2\22\1\0\2\22\1\0\1\45\1\22"+
    "\1\0\1\45\3\22\1\46\1\22\1\47\1\50\1\22"+
    "\1\0\1\22\2\0\1\44\1\51\2\52\1\22\2\53"+
    "\2\54\4\22\2\55\2\56\1\0\1\37\1\0\2\22"+
    "\1\57\1\22\1\60\1\22\2\0\1\37\1\61\1\62"+
    "\1\22\2\63\1\62\1\22\1\64";

  private static int [] zzUnpackAction() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\61\0\142\0\61\0\61\0\223\0\61"+
    "\0\61\0\61\0\61\0\61\0\61\0\304\0\365\0\u0126"+
    "\0\61\0\u0157\0\61\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c"+
    "\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4"+
    "\0\u0405\0\u0436\0\61\0\61\0\61\0\u0467\0\61\0\u0498"+
    "\0\u04c9\0\u04fa\0\u052b\0\u055c\0\u058d\0\u05be\0\61\0\61"+
    "\0\61\0\u05ef\0\u0620\0\u0651\0\u0682\0\u06b3\0\u02ae\0\u06e4"+
    "\0\u0715\0\u0746\0\u02ae\0\u0777\0\u07a8\0\u02ae\0\u02ae\0\u07d9"+
    "\0\u080a\0\u083b\0\u086c\0\u089d\0\u08ce\0\u08ff\0\61\0\u0930"+
    "\0\61\0\u052b\0\u0961\0\u0992\0\u09c3\0\u09f4\0\u0a25\0\u0a56"+
    "\0\u0a87\0\u02ae\0\61\0\u0ab8\0\u0ae9\0\u02ae\0\u0b1a\0\u0b4b"+
    "\0\u0b7c\0\u0bad\0\u0bde\0\u0c0f\0\u0c40\0\u02ae\0\u0c71\0\u0ca2"+
    "\0\u0cd3\0\u0d04\0\u0d35\0\u0d66\0\u0d97\0\u0dc8\0\u0df9\0\u0e2a"+
    "\0\u0e5b\0\u0e8c\0\u0ebd\0\u02ae\0\u0eee\0\u0f1f\0\61\0\u0f50"+
    "\0\u0f81\0\u0fb2\0\u02ae\0\u0fe3\0\u02ae\0\u02ae\0\u1014\0\u1045"+
    "\0\u1076\0\u10a7\0\u10d8\0\u1109\0\u02ae\0\u02ae\0\61\0\u113a"+
    "\0\u02ae\0\61\0\u02ae\0\61\0\u116b\0\u119c\0\u11cd\0\u11fe"+
    "\0\u02ae\0\61\0\u122f\0\u1260\0\u1291\0\u1109\0\u12c2\0\u12f3"+
    "\0\u1324\0\u02ae\0\u1355\0\u02ae\0\u1386\0\u13b7\0\u13e8\0\u1419"+
    "\0\u02ae\0\u02ae\0\u144a\0\u02ae\0\61\0\61\0\u147b\0\u02ae";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\2\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\3\32\1\33\2\32\1\34\1\32\1\35\1\36\1\37"+
    "\1\32\1\40\1\32\1\41\1\42\1\32\1\43\1\44"+
    "\1\2\1\45\1\46\1\2\6\47\1\50\1\47\1\51"+
    "\52\47\1\3\3\47\1\50\1\47\1\51\56\47\1\52"+
    "\1\47\1\53\56\47\1\50\1\47\1\51\3\47\1\54"+
    "\2\16\1\55\5\47\26\56\2\47\1\54\11\47\1\50"+
    "\1\47\1\51\4\47\3\17\5\47\26\56\14\47\1\50"+
    "\1\47\1\51\12\47\1\57\43\47\1\50\1\47\1\51"+
    "\12\47\1\60\43\47\1\50\1\47\1\51\12\47\1\61"+
    "\43\47\1\50\1\47\1\51\4\47\3\32\5\47\17\32"+
    "\1\62\6\32\14\47\1\50\1\47\1\51\4\47\3\32"+
    "\5\47\4\32\1\63\10\32\1\64\10\32\14\47\1\50"+
    "\1\47\1\51\4\47\3\32\5\47\15\32\1\65\10\32"+
    "\14\47\1\50\1\47\1\51\4\47\3\32\5\47\10\32"+
    "\1\66\4\32\1\67\10\32\4\47\1\70\7\47\1\50"+
    "\1\47\1\51\4\47\3\32\5\47\12\32\1\71\1\32"+
    "\1\72\11\32\14\47\1\50\1\47\1\51\4\47\3\32"+
    "\5\47\26\32\14\47\1\50\1\47\1\51\4\47\3\32"+
    "\5\47\5\32\1\73\6\32\1\74\11\32\14\47\1\50"+
    "\1\47\1\51\4\47\3\32\5\47\15\32\1\75\10\32"+
    "\14\47\1\50\1\47\1\51\4\47\3\32\5\47\5\32"+
    "\1\76\11\32\1\77\6\32\14\47\1\50\1\47\1\51"+
    "\4\47\3\32\5\47\17\32\1\100\6\32\14\47\1\50"+
    "\1\47\1\51\4\47\3\32\5\47\4\32\1\101\21\32"+
    "\14\47\1\50\1\47\1\51\4\47\3\32\5\47\7\32"+
    "\1\102\15\32\1\103\14\47\1\50\1\47\1\51\4\47"+
    "\3\32\5\47\1\104\25\32\14\47\1\50\1\47\1\51"+
    "\4\47\3\32\5\47\7\32\1\105\7\32\1\106\6\32"+
    "\14\47\1\50\1\47\1\51\21\47\1\107\6\47\1\110"+
    "\25\47\1\52\1\47\1\0\56\47\1\50\1\111\1\51"+
    "\56\47\1\52\1\47\1\51\50\47\10\112\1\113\50\112"+
    "\6\47\1\50\1\47\1\51\3\47\1\54\2\114\1\54"+
    "\35\47\1\54\11\47\1\50\1\47\1\51\3\47\1\54"+
    "\2\115\1\55\5\47\26\56\2\47\1\54\11\47\1\50"+
    "\1\47\1\51\4\47\3\56\5\47\26\56\14\47\1\50"+
    "\1\47\1\51\4\47\3\32\5\47\17\32\1\116\6\32"+
    "\14\47\1\50\1\47\1\51\4\47\3\32\5\47\6\32"+
    "\1\117\17\32\14\47\1\50\1\47\1\51\4\47\3\32"+
    "\5\47\15\32\1\120\10\32\14\47\1\50\1\47\1\51"+
    "\4\47\3\32\5\47\14\32\1\121\11\32\14\47\1\50"+
    "\1\47\1\51\4\47\3\32\5\47\23\32\1\122\2\32"+
    "\14\47\1\50\1\47\1\51\37\47\1\123\16\47\1\50"+
    "\1\47\1\51\4\47\3\32\5\47\20\32\1\124\5\32"+
    "\5\47\1\125\6\47\1\50\1\47\1\51\4\47\3\32"+
    "\5\47\3\32\1\126\22\32\14\47\1\50\1\47\1\51"+
    "\4\47\3\32\5\47\21\32\1\127\4\32\14\47\1\50"+
    "\1\47\1\51\4\47\3\32\5\47\3\32\1\130\22\32"+
    "\14\47\1\50\1\47\1\51\4\47\3\32\5\47\15\32"+
    "\1\131\10\32\14\47\1\50\1\47\1\51\4\47\3\32"+
    "\5\47\1\132\1\32\1\133\23\32\14\47\1\50\1\47"+
    "\1\51\4\47\3\32\5\47\4\32\1\134\21\32\14\47"+
    "\1\50\1\47\1\51\4\47\3\32\5\47\16\32\1\135"+
    "\7\32\14\47\1\50\1\47\1\51\4\47\3\32\5\47"+
    "\17\32\1\136\6\32\14\47\1\50\1\47\1\51\4\47"+
    "\3\32\5\47\10\32\1\137\15\32\4\47\1\140\7\47"+
    "\1\50\1\47\1\51\4\47\3\32\5\47\10\32\1\141"+
    "\15\32\4\47\1\142\7\47\1\50\1\47\1\51\35\47"+
    "\1\143\12\47\7\112\1\144\1\145\50\112\6\47\1\50"+
    "\1\47\1\51\4\47\3\114\47\47\1\50\1\47\1\51"+
    "\4\47\3\115\5\47\26\56\14\47\1\50\1\47\1\51"+
    "\4\47\3\32\5\47\1\146\25\32\14\47\1\50\1\47"+
    "\1\51\4\47\3\32\5\47\10\32\1\147\15\32\4\47"+
    "\1\150\7\47\1\50\1\47\1\51\4\47\3\32\5\47"+
    "\12\32\1\151\13\32\14\47\1\50\1\47\1\51\4\47"+
    "\3\32\5\47\20\32\1\152\5\32\5\47\1\153\6\47"+
    "\1\50\1\47\1\51\4\47\3\32\5\47\4\32\1\154"+
    "\3\32\1\155\15\32\4\47\1\156\7\47\1\50\1\47"+
    "\1\51\20\47\1\157\3\47\1\156\21\47\1\156\7\47"+
    "\1\50\1\47\1\51\4\47\3\32\5\47\4\32\1\160"+
    "\21\32\14\47\1\50\1\47\1\51\4\47\3\32\5\47"+
    "\22\32\1\161\3\32\14\47\1\50\1\47\1\51\4\47"+
    "\3\32\5\47\2\32\1\162\23\32\14\47\1\50\1\47"+
    "\1\51\4\47\3\32\5\47\3\32\1\163\22\32\14\47"+
    "\1\50\1\47\1\51\4\47\3\32\5\47\15\32\1\164"+
    "\10\32\14\47\1\50\1\47\1\51\4\47\3\32\5\47"+
    "\14\32\1\165\11\32\14\47\1\50\1\47\1\51\4\47"+
    "\3\32\5\47\4\32\1\166\21\32\14\47\1\50\1\47"+
    "\1\51\4\47\3\32\5\47\12\32\1\167\13\32\14\47"+
    "\1\50\1\47\1\51\26\47\1\170\27\47\1\50\1\47"+
    "\1\51\4\47\3\32\5\47\21\32\1\171\4\32\14\47"+
    "\1\50\1\47\1\51\35\47\1\172\20\47\1\50\1\47"+
    "\1\51\20\47\1\173\27\47\61\0\7\112\1\174\1\145"+
    "\50\112\6\47\1\50\1\47\1\51\4\47\3\32\5\47"+
    "\25\32\1\175\14\47\1\50\1\47\1\51\4\47\3\32"+
    "\5\47\14\32\1\176\11\32\14\47\1\50\1\47\1\51"+
    "\30\47\1\177\25\47\1\50\1\47\1\51\4\47\3\32"+
    "\5\47\4\32\1\200\21\32\14\47\1\50\1\47\1\51"+
    "\4\47\3\32\5\47\21\32\1\201\4\32\14\47\1\50"+
    "\1\47\1\51\35\47\1\202\20\47\1\50\1\47\1\51"+
    "\4\47\3\32\5\47\5\32\1\203\20\32\14\47\1\50"+
    "\1\47\1\51\21\47\1\204\34\47\1\50\1\47\1\51"+
    "\4\47\3\32\5\47\6\32\1\205\17\32\14\47\1\50"+
    "\1\47\1\51\4\47\3\32\5\47\12\32\1\206\13\32"+
    "\14\47\1\50\1\47\1\51\4\47\3\32\5\47\4\32"+
    "\1\207\21\32\14\47\1\50\1\47\1\51\4\47\3\32"+
    "\5\47\17\32\1\210\6\32\14\47\1\50\1\47\1\51"+
    "\4\47\3\32\5\47\4\32\1\211\21\32\14\47\1\50"+
    "\1\47\1\51\20\47\1\212\35\47\1\50\1\47\1\51"+
    "\4\47\3\32\5\47\4\32\1\213\21\32\14\47\1\50"+
    "\1\47\1\51\20\47\1\214\35\47\1\50\1\47\1\51"+
    "\22\47\1\215\25\47\10\216\1\217\50\216\6\47\1\50"+
    "\1\47\1\51\4\47\3\32\5\47\1\220\25\32\14\47"+
    "\1\50\1\47\1\51\4\47\3\32\5\47\4\32\1\221"+
    "\21\32\14\47\1\50\1\47\1\51\4\47\3\32\5\47"+
    "\4\32\1\222\21\32\14\47\1\50\1\47\1\51\4\47"+
    "\3\32\5\47\3\32\1\223\22\32\14\47\1\50\1\47"+
    "\1\51\4\47\3\32\5\47\3\32\1\224\22\32\14\47"+
    "\1\50\1\47\1\51\4\47\3\32\5\47\12\32\1\225"+
    "\13\32\14\47\1\50\1\47\1\51\26\47\1\226\27\47"+
    "\1\50\1\47\1\51\20\47\1\227\27\47\7\216\1\0"+
    "\1\230\50\216\6\47\1\50\1\47\1\51\4\47\3\32"+
    "\5\47\14\32\1\231\11\32\14\47\1\50\1\47\1\51"+
    "\4\47\3\32\5\47\17\32\1\232\6\32\14\47\1\50"+
    "\1\47\1\51\4\47\3\32\5\47\22\32\1\233\3\32"+
    "\14\47\1\50\1\47\1\51\4\47\3\32\5\47\14\32"+
    "\1\234\11\32\14\47\1\50\1\47\1\51\30\47\1\235"+
    "\25\47\1\50\1\47\1\51\33\47\1\236\14\47\10\216"+
    "\1\230\50\216\6\47\1\50\1\47\1\51\4\47\3\32"+
    "\5\47\17\32\1\237\6\32\14\47\1\50\1\47\1\51"+
    "\4\47\3\32\5\47\4\32\1\240\21\32\6\47";

  private static int [] zzUnpacktrans() {
    int [] result = new int[5292];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\45\1\5\0\14\1\1\0\17\1\1\0\2\1"+
    "\1\0\11\1\1\0\12\1\1\0\1\1\2\0\1\11"+
    "\3\1\1\0\2\1\1\0\2\1\1\0\11\1\1\0"+
    "\1\1\2\0\21\1\1\0\1\1\1\0\6\1\2\0"+
    "\11\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public OberonScanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public Token next_token() throws java.io.IOException
    , LexicalException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return Symbol.eof(yyline + 1, yycolumn + 1);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* Unknown symbol, read one character */
                        throw new IllegalSymbolException("Unknown symbol");
            }
          // fall through
          case 53: break;
          case 2:
            { /* Skip white spaces */
            }
          // fall through
          case 54: break;
          case 3:
            { return Operator.neq(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 55: break;
          case 4:
            { return Operator.and(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 56: break;
          case 5:
            { return Symbol.lpar(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 57: break;
          case 6:
            { return Symbol.rpar(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 58: break;
          case 7:
            { return Operator.mult(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 59: break;
          case 8:
            { return Operator.plus(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 60: break;
          case 9:
            { return Symbol.comma(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 61: break;
          case 10:
            { return Operator.minus(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 62: break;
          case 11:
            { return Symbol.dot(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 63: break;
          case 12:
            { /* Parse integer */

                        // Validate integer
                        if (!yytext().matches("[0-9]+")) {
                            throw new LexicalException("Invalid integer");
                        }

                        // Check integer length
                        if (yytext().length() > 12) {
                            throw new IllegalIntegerRangeException("Too long integer");
                        }

                        // Parse integer value
                        if (yytext().startsWith("0")) {
                            // Parse octal integer
                            try {
                                return new MyInteger(yyline + 1, yycolumn + 1, Integer.parseInt(yytext(), 8));
                            } catch (NumberFormatException e) {
                                throw new IllegalOctalException("Invalid octal integer");
                            }
                        } else {
                            // Parse decimal integer
                            try {
                                return new MyInteger(yyline + 1, yycolumn + 1, Integer.parseInt(yytext()));
                            } catch (NumberFormatException e) {
                                throw new IllegalIntegerException("Invalid decimal integer");
                            }
                        }
            }
          // fall through
          case 64: break;
          case 13:
            { return Symbol.colon(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 65: break;
          case 14:
            { return Symbol.semicol(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 66: break;
          case 15:
            { return Operator.lt(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 67: break;
          case 16:
            { return Operator.eq(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 68: break;
          case 17:
            { return Operator.gt(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 69: break;
          case 18:
            { /* Parse Identifier */

                        if (yylength() > 24) {
							throw new IllegalIdentifierLengthException("Too long identifier");
                        }

                        return new Identifier(yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 70: break;
          case 19:
            { return Symbol.lbrack(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 71: break;
          case 20:
            { return Symbol.rbrack(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 72: break;
          case 21:
            { return Operator.not(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 73: break;
          case 22:
            { throw new IllegalOctalException("Invalid octal integer");
            }
          // fall through
          case 74: break;
          case 23:
            { throw new IllegalIntegerException("Invalid decimal integer");
            }
          // fall through
          case 75: break;
          case 24:
            { return Operator.assign(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 76: break;
          case 25:
            { return Operator.lteq(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 77: break;
          case 26:
            { return Operator.gteq(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 78: break;
          case 27:
            { return Keyword.symDo(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 79: break;
          case 28:
            { return Keyword.symIf(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 80: break;
          case 29:
            { return Keyword.symOf(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 81: break;
          case 30:
            { return Operator.or(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 82: break;
          case 31:
            { throw new MismatchedCommentException("Open comment error");
            }
          // fall through
          case 83: break;
          case 32:
            { return Operator.div(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 84: break;
          case 33:
            { return Keyword.symEnd(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 85: break;
          case 34:
            { return Operator.mod(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 86: break;
          case 35:
            { return Keyword.symVar(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 87: break;
          case 36:
            { /* Skip comments */
            }
          // fall through
          case 88: break;
          case 37:
            { return Keyword.symElse(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 89: break;
          case 38:
            { return Keyword.symRead(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 90: break;
          case 39:
            { return Keyword.symThen(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 91: break;
          case 40:
            { return Keyword.symType(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 92: break;
          case 41:
            { return Keyword.typeArray(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 93: break;
          case 42:
            { return Keyword.symBegin(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 94: break;
          case 43:
            { return Keyword.symConst(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 95: break;
          case 44:
            { return Keyword.symElif(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 96: break;
          case 45:
            { return Keyword.symWhile(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 97: break;
          case 46:
            { return Keyword.symWrite(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 98: break;
          case 47:
            { return Keyword.symModule(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 99: break;
          case 48:
            { return Keyword.typeRecord(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 100: break;
          case 49:
            { return Keyword.typeBool(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 101: break;
          case 50:
            { return Keyword.typeInt(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 102: break;
          case 51:
            { return Keyword.symWriteln(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 103: break;
          case 52:
            { return Keyword.symProcedure(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 104: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
